// <auto-generated />
using System;
using EspaçoVerdeLogin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EspaçoVerdeLogin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250626031932_testeee")]
    partial class testeee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Localizacao", b =>
                {
                    b.Property<int>("ID_Localizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Localizacao"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Localizacao");

                    b.ToTable("Localizacoes");
                });

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Residuo", b =>
                {
                    b.Property<int>("ID_Residuo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Residuo"));

                    b.Property<int>("ID_Localizacao")
                        .HasColumnType("int");

                    b.Property<string>("ID_Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Residuo");

                    b.HasIndex("ID_Localizacao");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("Residuos");

                    b.HasData(
                        new
                        {
                            ID_Residuo = -1,
                            ID_Localizacao = 1,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "aco_inox.webp",
                            Nome = "Aço Inox",
                            PrecoKg = 5.50m,
                            Quantidade = 100m
                        },
                        new
                        {
                            ID_Residuo = -2,
                            ID_Localizacao = 2,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "ferro_fundido.webp",
                            Nome = "Ferro Fundido",
                            PrecoKg = 1.20m,
                            Quantidade = 50m
                        },
                        new
                        {
                            ID_Residuo = -3,
                            ID_Localizacao = 3,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "aluminio.webp",
                            Nome = "Alumínio",
                            PrecoKg = 3.80m,
                            Quantidade = 75m
                        },
                        new
                        {
                            ID_Residuo = -4,
                            ID_Localizacao = 4,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "cobre.webp",
                            Nome = "Cobre",
                            PrecoKg = 8.20m,
                            Quantidade = 30m
                        },
                        new
                        {
                            ID_Residuo = -5,
                            ID_Localizacao = 1,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "latao.webp",
                            Nome = "Latão",
                            PrecoKg = 4.50m,
                            Quantidade = 60m
                        },
                        new
                        {
                            ID_Residuo = -6,
                            ID_Localizacao = 2,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "zinco.webp",
                            Nome = "Zinco",
                            PrecoKg = 2.10m,
                            Quantidade = 40m
                        },
                        new
                        {
                            ID_Residuo = -7,
                            ID_Localizacao = 3,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "chumbo.webp",
                            Nome = "Chumbo",
                            PrecoKg = 1.80m,
                            Quantidade = 25m
                        },
                        new
                        {
                            ID_Residuo = -9,
                            ID_Localizacao = 1,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "niquel.webp",
                            Nome = "Níquel",
                            PrecoKg = 12.00m,
                            Quantidade = 10m
                        },
                        new
                        {
                            ID_Residuo = -10,
                            ID_Localizacao = 2,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "titanio.webp",
                            Nome = "Titânio",
                            PrecoKg = 25.00m,
                            Quantidade = 5m
                        },
                        new
                        {
                            ID_Residuo = -11,
                            ID_Localizacao = 3,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "bronze.webp",
                            Nome = "Bronze",
                            PrecoKg = 6.80m,
                            Quantidade = 12m
                        },
                        new
                        {
                            ID_Residuo = -12,
                            ID_Localizacao = 4,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "aco_carbono.webp",
                            Nome = "Aço Carbono",
                            PrecoKg = 0.90m,
                            Quantidade = 22m
                        },
                        new
                        {
                            ID_Residuo = -13,
                            ID_Localizacao = 1,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "magnesio.webp",
                            Nome = "Magnésio",
                            PrecoKg = 4.20m,
                            Quantidade = 18m
                        },
                        new
                        {
                            ID_Residuo = -14,
                            ID_Localizacao = 2,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "cromo.webp",
                            Nome = "Cromo",
                            PrecoKg = 7.10m,
                            Quantidade = 16m
                        },
                        new
                        {
                            ID_Residuo = -15,
                            ID_Localizacao = 3,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "manganes.webp",
                            Nome = "Manganês",
                            PrecoKg = 1.50m,
                            Quantidade = 20m
                        },
                        new
                        {
                            ID_Residuo = -17,
                            ID_Localizacao = 1,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "molibdenio.webp",
                            Nome = "Molibdênio",
                            PrecoKg = 28.00m,
                            Quantidade = 2m
                        },
                        new
                        {
                            ID_Residuo = -18,
                            ID_Localizacao = 2,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "vanadio.webp",
                            Nome = "Vanádio",
                            PrecoKg = 15.50m,
                            Quantidade = 7m
                        },
                        new
                        {
                            ID_Residuo = -19,
                            ID_Localizacao = 3,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "aco_inox.webp",
                            Nome = "Aço Inox",
                            PrecoKg = 5.70m,
                            Quantidade = 15m
                        },
                        new
                        {
                            ID_Residuo = -20,
                            ID_Localizacao = 4,
                            ID_Usuario = "9eada58b-13f5-45d3-be4b-c4d49fff8b2a",
                            ImgUrl = "aluminio.webp",
                            Nome = "Alumínio",
                            PrecoKg = 4.00m,
                            Quantidade = 50m
                        });
                });

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Transacao", b =>
                {
                    b.Property<int>("ID_Transacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Transacao"));

                    b.Property<DateTime>("Data_Transacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("ID_Comprador")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ID_Residuo")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco_Final")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Transacao");

                    b.HasIndex("ID_Comprador");

                    b.HasIndex("ID_Residuo")
                        .IsUnique();

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Users", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Residuo", b =>
                {
                    b.HasOne("EspaçoVerdeLogin.Models.Localizacao", "Localizacao")
                        .WithMany("Residuos")
                        .HasForeignKey("ID_Localizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EspaçoVerdeLogin.Models.Users", "Usuario")
                        .WithMany("Residuos")
                        .HasForeignKey("ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Transacao", b =>
                {
                    b.HasOne("EspaçoVerdeLogin.Models.Users", "Comprador")
                        .WithMany("TransacoesComoComprador")
                        .HasForeignKey("ID_Comprador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EspaçoVerdeLogin.Models.Residuo", "Residuo")
                        .WithOne("Transacao")
                        .HasForeignKey("EspaçoVerdeLogin.Models.Transacao", "ID_Residuo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Residuo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EspaçoVerdeLogin.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EspaçoVerdeLogin.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EspaçoVerdeLogin.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EspaçoVerdeLogin.Models.Users", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Localizacao", b =>
                {
                    b.Navigation("Residuos");
                });

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Residuo", b =>
                {
                    b.Navigation("Transacao")
                        .IsRequired();
                });

            modelBuilder.Entity("EspaçoVerdeLogin.Models.Users", b =>
                {
                    b.Navigation("Residuos");

                    b.Navigation("TransacoesComoComprador");
                });
#pragma warning restore 612, 618
        }
    }
}
